version: '3'
services:
  test-mysql:
    image: mysql
    expose:
      - "3306"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

networks:
  my-network:
    driver: bridge